// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function AddRoleForUser(arg1) {
  return window['go']['core']['CommandHandler']['AddRoleForUser'](arg1);
}

export function ConnectEngine(arg1, arg2, arg3, arg4) {
  return window['go']['core']['CommandHandler']['ConnectEngine'](arg1, arg2, arg3, arg4);
}

export function CreateDatabase(arg1) {
  return window['go']['core']['CommandHandler']['CreateDatabase'](arg1);
}

export function CreateLogin(arg1) {
  return window['go']['core']['CommandHandler']['CreateLogin'](arg1);
}

export function CreateTable(arg1) {
  return window['go']['core']['CommandHandler']['CreateTable'](arg1);
}

export function CreateUser(arg1) {
  return window['go']['core']['CommandHandler']['CreateUser'](arg1);
}

export function DropDatabase(arg1) {
  return window['go']['core']['CommandHandler']['DropDatabase'](arg1);
}

export function DropLogin(arg1) {
  return window['go']['core']['CommandHandler']['DropLogin'](arg1);
}

export function DropRoleForUser(arg1) {
  return window['go']['core']['CommandHandler']['DropRoleForUser'](arg1);
}

export function DropTable(arg1) {
  return window['go']['core']['CommandHandler']['DropTable'](arg1);
}

export function DropUser(arg1) {
  return window['go']['core']['CommandHandler']['DropUser'](arg1);
}

export function GetAllFromTable(arg1) {
  return window['go']['core']['CommandHandler']['GetAllFromTable'](arg1);
}

export function GetAppVersion() {
  return window['go']['core']['CommandHandler']['GetAppVersion']();
}

export function GetColumnsInfoByTableName(arg1) {
  return window['go']['core']['CommandHandler']['GetColumnsInfoByTableName'](arg1);
}

export function GetDatabaseById(arg1) {
  return window['go']['core']['CommandHandler']['GetDatabaseById'](arg1);
}

export function GetDatabaseInfo(arg1) {
  return window['go']['core']['CommandHandler']['GetDatabaseInfo'](arg1);
}

export function GetDatabases() {
  return window['go']['core']['CommandHandler']['GetDatabases']();
}

export function GetDatabasesByEngineId(arg1) {
  return window['go']['core']['CommandHandler']['GetDatabasesByEngineId'](arg1);
}

export function GetEngineById(arg1) {
  return window['go']['core']['CommandHandler']['GetEngineById'](arg1);
}

export function GetEngines() {
  return window['go']['core']['CommandHandler']['GetEngines']();
}

export function GetFormattedErrorModelUnused() {
  return window['go']['core']['CommandHandler']['GetFormattedErrorModelUnused']();
}

export function GetGuiConfig() {
  return window['go']['core']['CommandHandler']['GetGuiConfig']();
}

export function GetLogins() {
  return window['go']['core']['CommandHandler']['GetLogins']();
}

export function GetSupportedLanguages() {
  return window['go']['core']['CommandHandler']['GetSupportedLanguages']();
}

export function GetTablesByDatabase(arg1) {
  return window['go']['core']['CommandHandler']['GetTablesByDatabase'](arg1);
}

export function GetTrackingStateUnused() {
  return window['go']['core']['CommandHandler']['GetTrackingStateUnused']();
}

export function GetUserById(arg1) {
  return window['go']['core']['CommandHandler']['GetUserById'](arg1);
}

export function GetUsers() {
  return window['go']['core']['CommandHandler']['GetUsers']();
}

export function GetUsersByEngineId(arg1) {
  return window['go']['core']['CommandHandler']['GetUsersByEngineId'](arg1);
}

export function OpenResultsDirectory() {
  return window['go']['core']['CommandHandler']['OpenResultsDirectory']();
}

export function RemoveDatabase(arg1) {
  return window['go']['core']['CommandHandler']['RemoveDatabase'](arg1);
}

export function RemoveEngine(arg1) {
  return window['go']['core']['CommandHandler']['RemoveEngine'](arg1);
}

export function RemoveUser(arg1) {
  return window['go']['core']['CommandHandler']['RemoveUser'](arg1);
}

export function SaveDatabase(arg1) {
  return window['go']['core']['CommandHandler']['SaveDatabase'](arg1);
}

export function SaveEngine(arg1, arg2, arg3, arg4) {
  return window['go']['core']['CommandHandler']['SaveEngine'](arg1, arg2, arg3, arg4);
}

export function SaveLocale(arg1) {
  return window['go']['core']['CommandHandler']['SaveLocale'](arg1);
}

export function SaveSidebarMinimized(arg1) {
  return window['go']['core']['CommandHandler']['SaveSidebarMinimized'](arg1);
}

export function SaveUser(arg1, arg2, arg3) {
  return window['go']['core']['CommandHandler']['SaveUser'](arg1, arg2, arg3);
}

export function SetContext(arg1) {
  return window['go']['core']['CommandHandler']['SetContext'](arg1);
}

export function ShutdownConnection() {
  return window['go']['core']['CommandHandler']['ShutdownConnection']();
}
