

CREATE PROCEDURE BDEXAMEN.dbo.SPINSERTA_N_ALUMNOS
AS
BEGIN
	DECLARE @ALUMNO VARCHAR(30)
	DECLARE @CONTRASE VARCHAR(300)
    DECLARE @MATERIA VARCHAR(20)
    DECLARE @FINICIO DATE
    DECLARE @FENTREGA DATE
	DECLARE @CON INT
	DECLARE @AZARNOM INT
	DECLARE @AZARCONTRA INT
    DECLARE @AZARMAT INT
	SET @CON = 1
	WHILE @CON <= {{ . }}
	BEGIN
		SET @AZARNOM = RAND()*(5-1)+1
		SET @AZARCONTRA = RAND()*(20001-11000)+11000
        SET @AZARMAT = RAND()*(5-1)+1
        SET @FINICIO = GETDATE()
        SET @FENTREGA = GETDATE()
		SET @ALUMNO = CASE
		WHEN @AZARNOM = 1 THEN 'JOSE CARLOS'
		WHEN @AZARNOM = 2 THEN 'HERLAND MAURICIO'
		WHEN @AZARNOM = 3 THEN 'JONATHAN'
		ELSE 'MILTON'
	END
        SET @MATERIA = CASE
		WHEN @AZARMAT = 1 THEN 'BASE DE DATOS'
		WHEN @AZARMAT = 2 THEN 'INGLES'
		WHEN @AZARMAT = 3 THEN 'PROGRAMACION'
		ELSE 'CAMPOS MAGNETICOS'
	END
		SET @CONTRASE = CONCAT(LEFT(@ALUMNO,1), @AZARCONTRA)
		EXECUTE SPINSERTARALUMNOS @ALUMNO, @CONTRASE, @MATERIA, @FINICIO, @FENTREGA
		SET @CON = @CON +1
	END
END

